name: Dev Memes
on:
  schedule:
    - cron: "0 */6 * * *"
    
  push:
    branches: ["main"]

jobs:
  deploy:
    name: Update Dev Meme
    runs-on: ubuntu-latest
    steps:
      - name: Update meme
        uses: cgyinthehouse/dev-memes-for-README@latest
        with:
          fetch_num: 50
